function generatePDF(reviewData, reviewCard) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    doc.setFont("helvetica");
    doc.setFontSize(16);
    doc.setFillColor(30, 58, 138);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text("Formbondhu Submission", 20, 20);
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 30);
    doc.setDrawColor(30, 58, 138);
    doc.setLineWidth(0.5);
    doc.rect(10, 10, 190, 277);
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    let y = 50;
    for (const [key, value] of Object.entries(reviewData)) {
        const label = key.charAt(0).toUpperCase() + key.slice(1).replace('_', ' ');
        doc.setFont("helvetica", "bold");
        doc.text(`${label}:`, 20, y);
        doc.setFont("helvetica", "normal");

        if (typeof value === 'string' && (value.startsWith('http') || value.startsWith('data:image'))) {
            try {
                const imgData = value;
                doc.addImage(imgData, 'JPEG', 20, y + 5, 80, 60, undefined, 'FAST');
                y += 70;
            } catch (error) {
                doc.text("Image could not be loaded", 20, y + 5);
                y += 10;
                console.error('PDF Image Error:', error);
            }
        } else {
            const lines = doc.splitTextToSize(value, 170);
            doc.text(lines, 20, y + 5);
            y += lines.length * 5 + 5;
        }
        y += 5;
    }

    doc.setFillColor(229, 231, 235);
    doc.rect(0, 277, 210, 20, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text("Generated by Formbondhu - www.formbondhu.com", 20, 287);
    doc.text("Page 1 of 1", 180, 287);

    const pdfBlob = doc.output('blob');
    const pdfUrl = URL.createObjectURL(pdfBlob);
    reviewCard.setAttribute('data-pdf-url', pdfUrl);
}
